[package]
name = "jolt-inlines-blake3"
version = "0.1.0"
edition = "2021"
description = "BLAKE3 inline implementations for Jolt VM"

[features]
default = []
host = ["dep:ctor", "dep:tracer"]

[dependencies]
ctor = { workspace = true, optional = true }
tracer = { workspace = true, optional = true }

[dev-dependencies]
blake3.workspace = true
hex-literal.workspace = true
rand.workspace = true
tracer = { workspace = true, features = ["test-utils"] }
